# Generated by Django 4.1 on 2022-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "year",
                    models.CharField(
                        choices=[("2078", "78"), ("2077", "77"), ("2076", "76")],
                        max_length=20,
                    ),
                ),
                ("code_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("testing", "Testing"),
                            ("testing2", "Testing2"),
                            ("testing3", "Testing3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[("2078", "78"), ("2077", "77"), ("2076", "76")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_name",
                    models.CharField(
                        choices=[
                            ("testing", "Testing"),
                            ("testing2", "Testing2"),
                            ("testing3", "Testing3"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="FeeNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_name",
                    models.CharField(
                        choices=[
                            ("testing", "Testing"),
                            ("testing2", "Testing2"),
                            ("testing3", "Testing3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
            ],
        ),
    ]
