# Generated by Django 4.1 on 2022-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.CharField(max_length=200)),
            ],
        ),
    ]
