# Generated by Django 4.1 on 2022-11-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elearn", "0002_aboutadmin"),
    ]

    operations = [
        migrations.RemoveField(model_name="books", name="year",),
        migrations.RemoveField(model_name="eventnotification", name="batch_name",),
        migrations.RemoveField(model_name="feenotification", name="batch_name",),
        migrations.AddField(
            model_name="books",
            name="grade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="elearn.class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventnotification",
            name="grade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="elearn.class",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feenotification",
            name="grade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="elearn.class",
            ),
            preserve_default=False,
        ),
    ]
