# Generated by Django 4.1 on 2022-10-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearn", "0002_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
    ]
