# Generated by Django 4.1 on 2022-10-30 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_aboutadmin'),
        ('teacherapp', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearn.class'),
            preserve_default=False,
        ),
    ]
