# Generated by Django 4.1 on 2022-10-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_notes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.subject'),
        ),
    ]
